# Generated by Django 3.0.5 on 2020-06-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-dueDate']},
        ),
    ]
