# Generated by Django 3.0.5 on 2020-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_bill_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
